spring:
  application:
    name: mock-jurados
  jackson:
    time-zone: America/Bogota

server:
  port: ${PUERTO:8083}

logging:
  level:
    root: INFO
    com.selloLegitimo.MockJurados: DEBUG

grpc:
  elecciones:
    host: ${ELECCIONES_GRPC_HOST:localhost}
    port: ${ELECCIONES_GRPC_PORT:9090}

censo:
  service:
    url: ${CENSO_SERVICE_URL:}
